import { useEffect, useMemo, useState } from 'react'
import { analyzeCandidate, evaluateAnswer, generateQuestion, generateReport, hasAi } from './ai'
import { buildLocalReport, scoreChoice } from './logic'
import { getLocalQuestions } from './localQuestions'
import { deleteSession, listSessions, saveSession } from './storage'
import type { Difficulty, InterviewConfig, InterviewQuestion, InterviewReport, InterviewSession, InterviewTurn, Role } from './types'

const roles:Role[]=['Java 后端','前端开发','软件测试','产品经理','自定义岗位']
const defaultConfig:InterviewConfig={role:'Java 后端',customRole:'',difficulty:'中级',duration:20,resume:'',jd:''}
const uid=()=>crypto.randomUUID()
type SpeechRecognitionLike={lang:string;interimResults:boolean;onresult?:(event:{results:ArrayLike<{0:{transcript:string}}>} )=>void;onerror?:()=>void;onend?:()=>void;start:()=>void}
const SpeechRecognitionCtor=()=>((window as unknown as {SpeechRecognition?:new()=>SpeechRecognitionLike;webkitSpeechRecognition?:new()=>SpeechRecognitionLike}).SpeechRecognition||(window as unknown as {webkitSpeechRecognition?:new()=>SpeechRecognitionLike}).webkitSpeechRecognition)

function Header({page,setPage,session}:{page:string;setPage:(p:string)=>void;session?:InterviewSession}){
  return <header><button className="logo" onClick={()=>setPage('home')}><i>IL</i><span>InterviewLab <b>AI</b></span></button><nav><button onClick={()=>setPage('home')}>新面试</button><button onClick={()=>setPage('history')}>历史记录</button>{session?.status==='active'&&<button onClick={()=>setPage('interview')}>继续面试</button>}</nav><span className={`mode ${hasAi?'online':'local'}`}>{hasAi?'AI 已连接':'本地题库'}</span></header>
}
function Home({start,busy,error}:{start:(c:InterviewConfig)=>void;busy:boolean;error:string}){
 const [config,setConfig]=useState(defaultConfig)
 return <main className="home"><section className="hero"><div className="eyebrow">PERSONAL INTERVIEW COACH</div><h1>让每一次开口，<em>更接近 Offer</em></h1><p>动态追问、选择题测评、简历针对性提问与五维复盘。所有面试历史仅保存在你的浏览器。</p><div className="hero-stats"><span><b>30%</b>选择题</span><span><b>70%</b>开放问答</span><span><b>5维</b>能力报告</span></div></section><section className="setup card"><h2>创建一场模拟面试</h2><label>目标岗位</label><div className="chips">{roles.map(r=><button className={config.role===r?'active':''} onClick={()=>setConfig({...config,role:r})} key={r}>{r}</button>)}</div>{config.role==='自定义岗位'&&<input placeholder="输入岗位名称" value={config.customRole} onChange={e=>setConfig({...config,customRole:e.target.value})}/>}<div className="grid2"><div><label>难度</label><select value={config.difficulty} onChange={e=>setConfig({...config,difficulty:e.target.value as Difficulty})}><option>初级</option><option>中级</option><option>高级</option></select></div><div><label>时长</label><select value={config.duration} onChange={e=>setConfig({...config,duration:Number(e.target.value) as 10|20|30})}><option value="10">10 分钟</option><option value="20">20 分钟</option><option value="30">30 分钟</option></select></div></div><label>简历 / 项目经历（可选）</label><textarea value={config.resume} onChange={e=>setConfig({...config,resume:e.target.value})} placeholder="粘贴脱敏后的简历或项目经历，AI 会围绕它追问…"/><label>职位描述 JD（可选）</label><textarea value={config.jd} onChange={e=>setConfig({...config,jd:e.target.value})} placeholder="粘贴目标岗位要求…"/>{error&&<p className="error">{error}</p>}<button className="primary" disabled={busy} onClick={()=>start(config)}>{busy?'正在准备面试…':'开始模拟面试 →'}</button></section></main>
}
function Interview({session,setSession,finish}:{session:InterviewSession;setSession:(s:InterviewSession)=>void;finish:(latest?:InterviewSession)=>void}){
 const q=session.currentQuestion!; const [text,setText]=useState(''); const [selected,setSelected]=useState<string[]>([]); const [busy,setBusy]=useState(false); const [listening,setListening]=useState(false); const [error,setError]=useState('')
 const isOpen=q.type==='open_answer'; const progress=Math.min(95,Math.round(session.turns.length/(session.config.duration===10?6:session.config.duration===20?10:14)*100))
 const submit=async(skipped=false)=>{if(!skipped&&!isOpen&&!selected.length)return; if(!skipped&&isOpen&&!text.trim())return; setBusy(true);setError(''); const answer=isOpen?text:selected; let evaluation; try{if(isOpen&&hasAi)evaluation=await evaluateAnswer(q,text); else if(!isOpen)evaluation={score:scoreChoice(q,selected),feedback:'选择题将在最终报告中统一解析。',strengths:[],improvements:[],followUpNeeded:false}; const turns=[...session.turns,{question:q,answer,evaluation,skipped}]; if(turns.length>=(session.config.duration===10?6:session.config.duration===20?10:14)){const latest={...session,turns};setSession(latest);finish(latest);return} let next; if(hasAi)next=await generateQuestion(session.config,turns,turns.filter(t=>t.question.type!=='open_answer').length/turns.length<.3); else {const pool=getLocalQuestions(session.config.role,session.config.difficulty);next=pool[turns.length%pool.length]} setSession({...session,turns,currentQuestion:{...next,id:next.id||uid()}});setText('');setSelected([])}catch(e){setError(e instanceof Error?e.message:'提交失败，请重试')}finally{setBusy(false)}}
 const speak=()=>speechSynthesis.speak(new SpeechSynthesisUtterance(q.question))
 const dictate=()=>{const Ctor=SpeechRecognitionCtor();if(!Ctor){setError('当前浏览器不支持语音输入，请使用文字回答。');return}const recognition=new Ctor();recognition.lang='zh-CN';recognition.interimResults=false;recognition.onresult=e=>setText(value=>`${value}${value?' ':''}${e.results[0][0].transcript}`);recognition.onerror=()=>setError('语音识别未成功，请重试或使用文字回答。');recognition.onend=()=>setListening(false);setListening(true);recognition.start()}
 return <main className="interview"><section className="interview-top"><div><span>{session.config.role}</span><b>{session.config.difficulty} · {session.config.duration} 分钟</b></div><div className="progress"><i style={{width:`${progress}%`}}/></div><strong>{session.turns.length+1}</strong></section><section className="question card"><div className="qmeta"><span>{q.type==='open_answer'?'开放问答':q.type==='single_choice'?'单选题':'多选题'}</span><span>{q.topic}</span><button onClick={speak}>朗读问题</button>{isOpen&&<button disabled={listening} onClick={dictate}>{listening?'正在聆听…':'语音输入'}</button>}</div><h2>{q.question}</h2>{isOpen?<textarea className="answer" value={text} onChange={e=>setText(e.target.value)} placeholder="建议使用清晰的结构回答，可以结合具体项目与数据…"/>:<div className="options">{q.options?.map(o=><button className={selected.includes(o.id)?'selected':''} key={o.id} onClick={()=>setSelected(q.type==='single_choice'?[o.id]:selected.includes(o.id)?selected.filter(x=>x!==o.id):[...selected,o.id])}><b>{o.id}</b>{o.text}</button>)}</div>}{error&&<p className="error">{error}</p>}<div className="actions"><button onClick={()=>submit(true)}>跳过此题</button><button className="primary" disabled={busy} onClick={()=>submit()}>{busy?'AI 正在评估…':'提交回答'}</button><button onClick={()=>finish()}>提前结束</button></div></section><aside className="coach card"><h3>回答建议</h3><p>{isOpen?'先给出结论，再说明原因、方案取舍和实际结果。':'选择最符合题意的选项，整场结束后统一查看解析。'}</p><h3>本场主题</h3><div className="topics">{[...new Set(session.turns.map(t=>t.question.topic).concat(q.topic))].map(t=><span key={t}>{t}</span>)}</div></aside></main>
}
function Report({session,setPage}:{session:InterviewSession;setPage:(p:string)=>void}){const r=session.report!;const md=`# InterviewLab AI 面试报告\n\n总分：${r.totalScore}\n\n${r.summary}\n\n## 薄弱点\n${r.weaknesses.map(x=>`- ${x}`).join('\n')}`;return <main className="report"><section className="score card"><div className="ring"><b>{r.totalScore}</b><span>综合得分</span></div><div><span className="eyebrow">INTERVIEW REPORT</span><h1>{session.config.role} · {session.config.difficulty}</h1><p>{r.summary}</p><button onClick={()=>navigator.clipboard.writeText(md)}>复制报告</button></div></section><section className="dimensions card"><h2>能力雷达</h2>{Object.entries(r.dimensions).map(([k,v])=><div className="bar" key={k}><span>{k}</span><i><b style={{width:`${v}%`}}/></i><strong>{v}</strong></div>)}</section><section className="card"><h2>逐题复盘</h2>{session.turns.map((t,i)=><details key={i}><summary><span>{t.question.type==='open_answer'?'问答':'选择'}</span>{t.question.question}<b>{t.evaluation?.score??'-'} 分</b></summary><p><strong>你的回答：</strong>{Array.isArray(t.answer)?t.answer.join('、'):t.answer||'已跳过'}</p>{t.question.explanation&&<p><strong>正确答案：</strong>{t.question.correctAnswers?.join('、')} · {t.question.explanation}</p>}{t.evaluation?.feedback&&<p><strong>点评：</strong>{t.evaluation.feedback}</p>}</details>)}</section><section className="grid2 report-grid"><div className="card"><h2>薄弱知识点</h2>{r.weaknesses.map(x=><span className="tag" key={x}>{x}</span>)}</div><div className="card"><h2>下一步计划</h2><ol>{r.learningPlan.map(x=><li key={x}>{x}</li>)}</ol></div></section><button className="primary wide" onClick={()=>setPage('home')}>开始下一场面试</button></main>}
function History({open}:{open:(s:InterviewSession)=>void}){const [items,setItems]=useState<InterviewSession[]>([]);useEffect(()=>{listSessions().then(setItems)},[]);return <main className="history"><div className="page-title"><span className="eyebrow">LOCAL HISTORY</span><h1>面试历史</h1><p>记录仅保存在当前浏览器，可随时删除。</p></div><div className="history-grid">{items.map(s=><article className="card" key={s.id}><span>{new Date(s.startedAt).toLocaleDateString()}</span><h2>{s.config.role}</h2><p>{s.config.difficulty} · {s.turns.length} 题 · {s.aiMode?'AI 模式':'本地模式'}</p><strong>{s.report?.totalScore??'进行中'}</strong><div><button onClick={()=>open(s)}>查看</button><button onClick={async()=>{await deleteSession(s.id);setItems(await listSessions())}}>删除</button></div></article>)}</div>{!items.length&&<div className="empty card">还没有面试记录，开始第一场练习吧。</div>}</main>}
export default function App(){const [page,setPage]=useState('home');const [session,setSessionState]=useState<InterviewSession>();const [busy,setBusy]=useState(false);const [error,setError]=useState('');const setSession=(s:InterviewSession)=>{setSessionState(s);saveSession(s)};const start=async(config:InterviewConfig)=>{setBusy(true);setError('');try{let profile; if(hasAi&&(config.resume||config.jd))profile=await analyzeCandidate(config);const pool=getLocalQuestions(config.role,config.difficulty);let current=pool[0];if(hasAi)current=await generateQuestion(config,[],true);const s:InterviewSession={id:uid(),config,profile,turns:[],currentQuestion:{...current,id:current.id||uid()},startedAt:Date.now(),status:'active',aiMode:hasAi};setSession(s);setPage('interview')}catch(e){setError(e instanceof Error?e.message:'无法开始面试')}finally{setBusy(false)}};const finish=async(latest?:InterviewSession)=>{const source=latest??session;if(!source)return;setBusy(true);let report:InterviewReport;try{report=hasAi?await generateReport(source.config,source.turns):buildLocalReport(source.turns)}catch{report=buildLocalReport(source.turns)}const done={...source,status:'completed' as const,report};setSession(done);setPage('report');setBusy(false)};const content=useMemo(()=>page,[page]);return <><Header page={content} setPage={setPage} session={session}/>{page==='home'&&<Home start={start} busy={busy} error={error}/>} {page==='interview'&&session&&<Interview session={session} setSession={setSession} finish={finish}/>} {page==='report'&&session?.report&&<Report session={session} setPage={setPage}/>} {page==='history'&&<History open={s=>{setSessionState(s);setPage(s.report?'report':'interview')}}/>}<footer>InterviewLab AI · 你的个人面试训练场</footer></>}
